org: inukko
app: myapp
service: my-service
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  memorySize: 128
  # # Stage name
  # stage: staging
  # # Global environment variables
  # environment:
  #   MyGlobalEnv: MyGlobalEnvValue
  # # Additional IAM Permissions
  # iamRoleStatements:
  # - Effect: Allow
  #   Action:
  #   - ec2:DescribeInstances
  #   Resource: "*"
plugins:
  - serverless-webpack
  - serverless-offline
custom:
  webpackIncludeModules: true
functions:
  diceRoll:
    handler: handlers/diceRoll.default
    events:
      - http:
          path: diceRoll
          method: get
    # # Function specific environment variables
    # environment:
    #   MyPerFunctionEnv: foo
